# Generated by Django 2.2.3 on 2020-04-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20200425_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('german', 'German'), ('swahili', 'Swahili'), ('spanish', 'Spanish')], max_length=2),
        ),
    ]
